# Generated by Django 5.0.7 on 2024-07-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='group',
        ),
        migrations.AddField(
            model_name='staffs',
            name='groups',
            field=models.ManyToManyField(to='student_management_app.group'),
        ),
    ]
