# Generated by Django 5.0.7 on 2024-07-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='gender',
            field=models.CharField(default='male', max_length=50),
        ),
        migrations.AddField(
            model_name='staffs',
            name='profile_pic',
            field=models.FileField(default=' ', upload_to=''),
        ),
    ]
