# Generated by Django 5.0.7 on 2024-07-27 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_remove_staffs_group_staffs_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='encadrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.staffs'),
        ),
    ]
