# Generated by Django 5.0.7 on 2024-07-27 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_alter_project_encadrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='student_management_app.project'),
        ),
    ]
