# Generated by Django 5.0.7 on 2024-07-15 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_alter_staffs_admin_alter_students_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.courses'),
        ),
    ]
