# Generated by Django 5.0.7 on 2024-07-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_remove_certificat_course_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificat',
            name='certificate_file',
        ),
    ]
