# Generated by Django 5.0.7 on 2024-07-15 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_remove_leavereportstaff_staff_id_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.group'),
        ),
    ]
