# Generated by Django 5.0.7 on 2024-07-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_staffs_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=10),
        ),
    ]
