# Generated by Django 5.0.7 on 2024-07-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_group_day_of_week_alter_group_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='preferred_category',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='morning', max_length=10),
        ),
    ]
