# Generated by Django 5.0.7 on 2024-07-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_alter_group_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='code_PPR',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='grade',
            field=models.CharField(choices=[('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université'), ('superieure', 'Supérieure')], default='primaire', max_length=20),
        ),
    ]
