# Generated by Django 5.0.7 on 2024-07-17 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_students_code_ppr_students_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='grade',
            field=models.CharField(choices=[('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université'), ('superieure', 'Supérieure')], max_length=20),
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='certificates/')),
                ('course_name', models.CharField(max_length=255)),
                ('staff_name', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=50)),
                ('feedback', models.TextField()),
                ('organization_name', models.CharField(default='C.M.C.F', max_length=255)),
                ('course_date', models.DateField()),
                ('director_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='student_management_app.students')),
            ],
        ),
    ]
