# Generated by Django 5.0.7 on 2024-07-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0017_attendance_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='code_PPR',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
