# Generated by Django 5.0.7 on 2024-07-18 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0018_alter_students_code_ppr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='student_management_app.courses'),
        ),
    ]
