# Generated by Django 5.0.7 on 2024-07-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0019_alter_group_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='group',
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='groups', to='student_management_app.students'),
        ),
    ]
