# Generated by Django 5.0.7 on 2024-07-20 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0021_remove_group_students_students_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.group'),
        ),
    ]
