# Generated by Django 5.0.7 on 2024-07-20 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0024_note_delete_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='assignment_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='exam_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
