# Generated by Django 5.0.7 on 2024-07-20 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0025_studentresult_assignment_marks_studentresult_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses'),
        ),
    ]
