# Generated by Django 5.0.7 on 2024-07-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0027_remove_note_created_at_remove_note_note_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='assignment_marks',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='exam_marks',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='assignment_note',
            field=models.TextField(default=0.0),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='exam_note',
            field=models.TextField(default=0.0),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
