# Generated by Django 5.0.7 on 2024-07-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0028_rename_student_id_studentresult_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='assignment_note',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='exam_note',
        ),
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(to='student_management_app.courses'),
        ),
    ]
