# Generated by Django 5.0.7 on 2024-07-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0029_remove_studentresult_assignment_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='reference',
            field=models.CharField(default='Rabat Sale zamour zaer', max_length=100),
        ),
    ]
