# Generated by Django 5.0.7 on 2024-07-21 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0031_project_students_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='students',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='student_management_app.students'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default='0.00'),
        ),
    ]
