# Generated by Django 5.0.7 on 2024-07-22 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0033_alter_staffs_admin_alter_students_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='courses',
        ),
        migrations.AddField(
            model_name='students',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.courses'),
        ),
    ]
