# Generated by Django 5.0.7 on 2024-07-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0034_remove_students_courses_students_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='course',
        ),
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='student_management_app.courses'),
        ),
    ]
