# Generated by Django 5.0.7 on 2024-07-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0038_alter_certificat_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=555),
        ),
    ]
