# Generated by Django 5.0.7 on 2024-07-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0040_remove_group_course_group_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='courses',
            field=models.ManyToManyField(to='student_management_app.courses'),
        ),
    ]
