# Generated by Django 5.0.7 on 2024-07-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0041_alter_group_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('category', models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.group')),
            ],
            options={
                'unique_together': {('group', 'day_of_week', 'start_time', 'end_time', 'category')},
            },
        ),
    ]
